version: '3.9'

services:

  backuper:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes: 
      - $PATH_CONFIG_FILE:/app/config.json
      - $PATH_OUTPUT_DIR:/app/output