version: '3.7'

services:

  backuper:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      SCHEDULE: "\"* * * * *\""
      HOSTNAME: db
      DATABASE: mydb
      USERNAME: root
      PASSWORD: secret
      PORT: 3306
    volumes: 
      - /tmp/backup:/var/backup
  
  db:
    image: mariadb:10.4.4-bionic
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: secret